### ISSUE TITLE
PCB files cannot be opened.

### ISSUE THREAD

**Issue by theshadowsvk** [PaddyCube/WirelessWeather#1]
Hello PaddyCube, first of all, thank you for your great project !! All your solutions done in this project are simply perfect !! 
My issue is, I can't oped the PCB files, especially those KiCad (it needs .zip filed them in some sort of way) or Eagle files, that this EDA wants them to be saved in Eagle 6.0 or above.
I'm trying to import these in EasyEDA. If you have some time, can you check it please ?

Thank you,
Lubos

**Comment by PaddyCube** [comment]
Hello,
thank you for your feedback. Saldy I didn't note it, sorry for my late response. I'm not sure if I understand you right. I didn't create a PCB, its just a schematics drawing and I used KiCad to greate schematics. Currently, I don't know how to create a PCB file so you can manufacture it.

But as an additional note: I'm working on a ESP32 version of my weather station. That way, I can at least drop the two ATTINY85 because I use ULP co-processor to count while sleep.

**Comment by theshadowsvk** [comment]
Oh sorry I thought they are pcb files. I already re-created the schematics and started creating pcb. Btw, I do some enhancements there like light sensor on i2c bus and other things like easier voltage regulator, solar charge

Esp32 supports various deepsleeps

**Comment by PaddyCube** [comment]
May I ask which voltage regulator you use? MCP1703 does a good job but it delivers not enough current (250mA max). Sometimes, ESP8266 with all three Attinys will brownout and I must hard reset everything. I'm looking for a larger LDO for ESP32, so any suggestions?

**Comment by PaddyCube** [comment]
Only schematics are available. I used prototype boards to solder everything together. Meaning there is no ready-to use PCB file
